name: prtreid_train
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - numpy<2
  - pip:
      - -r requirements/requirements.txt
